Use SISACMPL;
--Update Usuario Set ApMaterno = 'Boyás' Where IdUsuario = 4;
Select * From Usuario;
Select * From Area;
Select * From Cargo;
Select * From Rol;
Use SISACMPL;
--Delete correspondencia where IdCorrespondencia=8;
Select * From correspondencia;
Select * From dependencia;
Select * From entidad_externa;
Select * From oficio_entrante;
Select * From anexo;
Select * From cargo_tiene_area;
Select * From entidad_externa;
